/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.synaptictools.traceroute;

public class TracerouteNative {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TracerouteNative(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TracerouteNative obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        traceroutelibJNI.delete_TracerouteNative(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    traceroutelibJNI.TracerouteNative_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    traceroutelibJNI.TracerouteNative_change_ownership(this, swigCPtr, true);
  }

  public TracerouteNative() {
    this(traceroutelibJNI.new_TracerouteNative(), true);
    traceroutelibJNI.TracerouteNative_director_connect(this, swigCPtr, true, true);
  }

  public static TracerouteNative instance() {
    return new TracerouteNative(traceroutelibJNI.TracerouteNative_instance(), false);
  }

  public int execute(StringVector args) {
    return traceroutelibJNI.TracerouteNative_execute(swigCPtr, this, StringVector.getCPtr(args), args);
  }

  public void onAppendResult(String result) {
    if (getClass() == TracerouteNative.class) traceroutelibJNI.TracerouteNative_onAppendResult(swigCPtr, this, result); else traceroutelibJNI.TracerouteNative_onAppendResultSwigExplicitTracerouteNative(swigCPtr, this, result);
  }

  public void onClearResult() {
    if (getClass() == TracerouteNative.class) traceroutelibJNI.TracerouteNative_onClearResult(swigCPtr, this); else traceroutelibJNI.TracerouteNative_onClearResultSwigExplicitTracerouteNative(swigCPtr, this);
  }

}
